system:
  user:
    name: yangchao
    sex: man
    age: 22

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.dev.car-house.cn:3306/car_house?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: carhouse-database
    password: root
  redis:
    database: 11
    host: 192.168.0.162
    password:
    port: 6379
    pool:
      jedis:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  output:
  ansi:
  enabled: DETECT

### 服务器地址
server:
    address: 127.0.0.1
    port: 8080

### 日志
debug: true
logging:
  file: my.log
  path: /var/log
  level:
    com:
      example:
        autocodetemplate: debug
